config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index', to: 'schedules#index'
  get 'schedules/new', to: 'schedules#new'

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence:true
  validates :start_date, presence:true
  validates :end_date, presence:true
  validates :title, length: { maximum:20 }
  validates :memo, length: { maximum:500 }
  validate :end_date_cannot_be_before_the_start_date

  def end_date_cannot_be_before_the_start_date
    if end_date < start_date
      errors.add(:end_date, "は開始日より前に設定してください")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
    @schedules_count = Schedule.count
    @today = Time.zone.today
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
    if @schedule.save
      flash[:notice] = "予定を登録しました"
      redirect_to :schedules
    else
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
      flash[:notice] = "id:#{@schedule.id}の予定を更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :schedules
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <p>スケジュール管理アプリ</p>
    </header>

    
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<%= render "shared/error", obj: @schedule %>

<div class="edit-container">

  <h2>予定編集</h2>

  <%= form_with model: @schedule do |f| %>
    <div class="row mb-3">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
    </div>

    <div class="mb-3">
      <%= f.label :start_date, "開始日" %>
      <%= f.date_select :start_date %>
    </div>

    <div class="mb-3">
      <%= f.label :end_date, "終了日" %>
      <%= f.date_select :end_date %>
    </div>

    <div class="mb-3">
      <%= f.label :all_day, "終日" %>
      <%= f.check_box :all_day %>
    </div>

    <div class="row mb-3">
      <%= f.label :memo, "メモ" %>
      <%= f.text_area :memo %>
    </div>

    <div class="link">
      <ul>
        <li><%= f.submit "編集完了" %></li>
        <li><%= link_to "一覧に戻る", schedules_path, class:"link" %></li>
      </ul>
    </div>

    <% end %>
</div>

app/views/schedules/index.html.erb
<div class = "index-container">
  
  <% if flash[:notice] %>
    <p class = "notice"><%= flash[:notice] %></p>
  <% end %>

  <div class="button-wrapper">
    <p>予定一覧</p>
    <%= button_to "新規登録", schedules_new_path, method: :get, class:"btn btn-primary" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日時</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.id %></td>
          <td><%= schedule.title %></td>
          <td><%= l schedule.start_date %></td>
          <td><%= l schedule.end_date %></td>
          <td>
            <% if schedule.all_day == true %>
              ○
            <% end %>
          </td>
          <td><%= l schedule.updated_at %></td>
          <td>
            <%= link_to "詳細", schedule_path(schedule), class:"link" %>
            <%= link_to "編集", edit_schedule_path(schedule), class:"link" %>
            <%= link_to "削除", schedule_path(schedule), class:"link", method: :delete, data:{ confirm:"本当に削除しますか？" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="footer">
  <p>予定合計：<span class="schedules-count"><%= @schedules_count %></span></p>
  <p>今日の日付：<span class="today"><%= l @today %></span></p>
  </div>

</div>

app/views/schedules/new.html.erb
<%= render "shared/error", obj: @schedule %>

<div class="new-container">

  <h2>予定登録</h2>

  <%= form_with model: @schedule do |f| %>
    <div class="row mb-3">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
    </div>

    <div class="mb-3">
      <%= f.label :start_date, "開始日" %>
      <%= f.date_select :start_date %>
    </div>

    <div class="mb-3">
      <%= f.label :end_date, "終了日" %>
      <%= f.date_select :end_date %>
    </div>

    <div class="mb-3">
      <%= f.label :all_day, "終日" %>
      <%= f.check_box :all_day %>
    </div>

    <div class="row mb-3">
      <%= f.label :memo, "メモ" %>
      <%= f.text_area :memo %>
    </div>    

    <div class="link">
      <ul>
        <li><%= f.submit "登録" %></li>
        <li><%= link_to "一覧に戻る", schedules_path ,class:"link"%></li>
      </ul>
    </div>

  <% end %>

</div>

app/views/schedules/show.html.erb
<div class ="show-container">

  <h2>予定詳細</h2>

  <table class="show-table table table-borderless">
    <tr>
      <th>タイトル</th>
      <td><%= @schedule.title %></td>
    </tr>
    <tr>
      <th>開始日</th>
      <td><%= l @schedule.start_date %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td><%= l @schedule.end_date %></td>
    </tr>
    <tr>
      <th>終日</th>
      <td>
        <% if @schedule.all_day == true %>
        ○
        <% end %>
      </td>
    </tr>
    <tr>
      <th>メモ</th>
      <td><%= @schedule.memo %></td>
    </tr>
  </table>

  <div class="link">
    <ul>
      <li><%= link_to "編集", edit_schedule_path(@schedule), class:"link" %></li>
      <li><%= link_to "一覧に戻る", schedules_path, class:"link" %></li>
    </ul>
  </div>

</div>

app/views/shared/_error.html.erb
<div class="error">
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
    <% end %>
<% end %>
</div>